# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KemiBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hashtags', models.TextField()),
                ('status', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=50)),
                ('KemiBox_type', models.CharField(choices=[('Regular', 'Regular'), ('Once And Done', 'Once And Done'), ('Date Range', 'Date Range')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(null=True, upload_to='media')),
                ('last_posted', models.DateTimeField(null=True)),
                ('kemibox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialadmin.KemiBox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
